server:
  port: 8086
spring:
  application:
    name: el-aparato
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/el-aparato-serrana-marset
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elaparato?createDatabaseIfNotExist=true
    username: root
    password: Serra2022
  sql:
    init:
      mode: always
      platform: mysql
      continue-on-error: true
  error:
    includes:
      message: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            orm:
              jpa: DEBUG
