server:
  port: 8181

spring:
  application:
    name: keycloak-admin

dh:
  keycloak:
    serverUrl: http://localhost:8080
    realm: el-aparato-serrana-marset
    clientId: api-internal-users-client
    clientSecret: 0bDmNgD6UP8LZkYaS4LFidl4c57YOJI3
